spring:
  cloud:
    gateway:
      #自动生成路由表
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-front
          uri: lb://user-front
          order: 0
          predicates:
            - Path=/user-front/**
          filters:
            - StripPrefix=0
            #熔断
            - name: CircuitBreaker
              args:
                name: gateway-circuitbreak
                fallbackUri: forward:/fallback
            #限流
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                #令牌桶每秒填充平均速率
                redis-rate-limiter.replenishRate: 1
                #令牌桶容量
                redis-rate-limiter.burstCapacity: 2
            #重试
            - name: Retry
              args:
                #重试次数
                retries: 2
                #状态码配置，默认值是 SERVER_ERROR，匹配 5xx
                series:
                  - CLIENT_ERROR
                  - SERVER_ERROR
                methods:
                  - GET
                  - POST