version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    image: elk_elasticsearch
    container_name: elk_elasticsearch
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - ifp3

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    image: elk_logstash
    container_name: elk_logstash
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - ifp3
    depends_on:
      - elasticsearch
      - kafka-zookeeper

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    image: elk_kibana
    container_name: elk_kibana
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - ifp3
    depends_on:
      - elasticsearch

  kafka-zookeeper:
    build:
      context: kafka/
    image: kafka-zookeeper
    container_name: kafka-zookeeper
    # If using docker machine, uncomment the below and set your bootstrap
    # server list to 192.168.99.100:19092
    # environment:
      # - KAFKA_ADVERTISED_HOST_NAME=192.168.99.100
    ports:
      - 2181:2181
      - 9092:9092
      # port 19092 is listening on localhost by default. In normal Docker,
      # you can set your bootstrap server list to localhost:19092
      - 19092:19092
    networks:
      - ifp3

  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is disabled by default.
  zipkin:
    build:
      context: zipkin/
    image: zipkin
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      # Uncomment to enable scribe
      # - SCRIBE_ENABLED=true
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin2=DEBUG
      - STORAGE_TYPE=elasticsearch
      # Point the zipkin at the storage backend
      - ES_HOSTS=elasticsearch:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=changeme
      # Uncomment to see requests to and from elasticsearch
      # - ES_HTTP_LOGGING=BODY
      - KAFKA_BOOTSTRAP_SERVERS=kafka-zookeeper:9092
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
      # Uncomment if you set SCRIBE_ENABLED=true
      # - 9410:9410
    networks:
      - ifp3
    depends_on:
      - kafka-zookeeper
      - elasticsearch

  # Adds a cron to process spans since midnight every hour, and all spans each day
  # This data is served by http://192.168.99.100:8080/dependency
  #
  # For more details, see https://github.com/openzipkin/docker-zipkin-dependencies
  zipkin-dependencies:
    #image: openzipkin/zipkin-dependencies
    build:
      context: zipkin-dependencies/
    image: zipkin-dependencies
    container_name: zipkin-dependencies
    entrypoint: crond -f
    environment:
      - STORAGE_TYPE=elasticsearch
      # Point the zipkin at the storage backend
      - ES_HOSTS=elasticsearch:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=changeme
      # Uncomment to see dependency processing logs
      # - ZIPKIN_LOG_LEVEL=DEBUG
      # Uncomment to adjust memory used by the dependencies job
      # - JAVA_OPTS=-verbose:gc -Xms1G -Xmx1G
    networks:
      - ifp3
    depends_on:
      - elasticsearch

  redis:
    image: redis:5.0.9
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - ifp3

  consul-1:
    image: consul:1.8.0
    container_name: consul-1
    volumes:
      - type: bind
        source: ./consul/config.json
        target: /consul/config/config.json
        read_only: true
      - type: volume
        source: consul_data_1
        target: /consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: consul agent -node=consul-server-1 -config-dir=/consul/config
    ports:
      - 8500:8500
      - 8600:8600
      - 8300:8300
      - 8301:8301
      - 8302:8302
    networks:
      ifp3: 
        aliases:
          - consul.network

  consul-2:
    image: consul:1.8.0
    container_name: consul-2
    volumes:
      - type: bind
        source: ./consul/config.json
        target: /consul/config/config.json
        read_only: true
      - type: volume
        source: consul_data_2
        target: /consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: consul agent -node=consul-server-2 -config-dir=/consul/config -retry-join=consul.network
    ports:
      - 8510:8500
      - 8610:8600
      - 8310:8300
      - 8311:8301
      - 8312:8302
    networks:
      - ifp3

  consul-3:
    image: consul:1.8.0
    container_name: consul-3
    volumes:
      - type: bind
        source: ./consul/config.json
        target: /consul/config/config.json
        read_only: true
      - type: volume
        source: consul_data_3
        target: /consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: consul agent -node=consul-server-3 -config-dir=/consul/config -retry-join=consul.network
    ports:
      - 8520:8500
      - 8620:8600
      - 8320:8300
      - 8321:8301
      - 8322:8302
    networks:
      - ifp3

  prometheus:
    image: prom/prometheus:v2.19.2
    container_name: prometheus
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
      - type: volume
        source: prometheus_data
        target: /prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      #- '--web.console.libraries=/usr/share/prometheus/console_libraries'
      #- '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - ifp3
    restart: always    

  grafana:
    image: grafana/grafana:7.0.5
    container_name: grafana
    env_file:
      - ./grafana/config.monitoring
    volumes:
      - type: bind
        source: ./grafana/provisioning/
        target: /etc/grafana/provisioning/
        read_only: true
      - type: volume
        source: grafana_data
        target: /var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - ifp3 
    depends_on:
      - prometheus

  ifp-config:
    build:
      context: ifp-config/
    image: ifp-config
    container_name: ifp-config
    volumes:
      - type: bind
        source: ./ifp-config/config-repo
        target: /config-repo
        read_only: true
    environment:
      - KAFKA_ZK=kafka-zookeeper:2181
      - KAFKA_URL=kafka-zookeeper:9092
      - CONSUL_URL=consul-1
    ports:
      - 7070:7070
    networks:
      - ifp3
    depends_on:
      - kafka-zookeeper
      - consul-1
      - consul-2
      - consul-3

  ifp-gateway:
    build:
      context: ifp-gateway/
    image: ifp-gateway
    container_name: ifp-gateway
    environment:
      - KAFKA_ZK=kafka-zookeeper:2181
      - KAFKA_URL=kafka-zookeeper:9092
      - CONSUL_URL=consul-1
    ports:
      - 8080:8080
    networks:
      - ifp3
    depends_on:
      - kafka-zookeeper
      - consul-1
      - consul-2
      - consul-3
      - ifp-config
      - redis
    restart: always

networks:
  ifp3:
    driver: bridge

volumes:
  elasticsearch:
  consul_data_1:
  consul_data_2:
  consul_data_3:
  prometheus_data:
  grafana_data:
