version: '3.2'

services:

  prometheus:
    image: prom/prometheus:v2.19.2
    container_name: prometheus
    volumes:
      - type: bind
        source: ./prometheus/
        target: /etc/prometheus/
        read_only: true
      - type: volume
        source: prometheus_data
        target: /prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      #- '--web.console.libraries=/usr/share/prometheus/console_libraries'
      #- '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - ifp3
    depends_on:
      - alertmanager
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    networks:
      - ifp3

  grafana:
    image: grafana/grafana:7.0.5
    container_name: grafana
    env_file:
      - ./grafana/config.monitoring
    volumes:
      - type: bind
        source: ./grafana/provisioning/
        target: /etc/grafana/provisioning/
        read_only: true
      - type: volume
        source: grafana_data
        target: /var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - ifp3 
    depends_on:
      - prometheus

networks:
  ifp3:
    driver: bridge
    external: true

volumes:
  prometheus_data:
  grafana_data:
